# Generated by Django 2.2.6 on 2019-11-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.DateField()),
                ('pol', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=10)),
                ('specialite', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vibor_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.users')),
                ('vibor_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.vibor_test')),
            ],
        ),
        migrations.CreateModel(
            name='stimul_slov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stimulus', models.CharField(max_length=200)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.vibor_test')),
            ],
        ),
        migrations.CreateModel(
            name='otvet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('stimul_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.stimul_slov')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.vibor_test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.users')),
            ],
        ),
    ]
